language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t awejocko/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true awejocko/docker-react npm run test